name: Deploy Microservices

on:
  push:
    branches:
      - main
    paths:
      - services/**

env:
  CLUSTER_NAME: eks-us-east-1
  REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [user, product, order]

    if: contains(github.event.head_commit.message, matrix.service)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}-service
          docker build -t $IMAGE_NAME ./services/${{ matrix.service }}
          docker push $IMAGE_NAME

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy to EKS with Helm
        run: |
          helm upgrade --install ${{ matrix.service }}-service ./services/${{ matrix.service }}/chart \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}-service \
            --set image.tag=latest \
            --namespace ${{ matrix.service }} --create-namespace

